---
abstract: 'generate some data in RDFa'
author:
  - '<http://purl.org/NET/cpan-uri/person/tobyink>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::More: 0.61
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 0
generated_by: 'Module::Install version 1.06'
keywords:
  - Generator
  - HTML
  - Output
  - RDF
  - RDFa
  - 'Semantic Web'
  - Serialiser
  - Serializer
  - Writer
  - XHTML
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: RDF::RDFa::Generator
name: RDF-RDFa-Generator
no_index:
  directory:
    - examples
    - inc
    - t
requires:
  Data::Dumper: 0
  Icon::FamFamFam::Silk: 0
  RDF::Prefixes: 0
  RDF::Trine: 0.112
  XML::LibXML: 1.60
  perl: 5.8.0
resources:
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=RDF-RDFa-Generator
  homepage: https://metacpan.org/release/RDF-RDFa-Generator
  license: http://dev.perl.org/licenses/
  repository: https://bitbucket.org/tobyink/p5-rdf-rdfa-generator
version: 0.103
